System:
  name: FastAmazingAcmeStorage 9000
  description: <text>
  storage_location: [ remote | local | hyper-converged ]
  client_software: [ in-box | proprietary ]
  storage_interface: [ block | file | object ]
  required_rack_units:
  shared_capabilities:
    multi_host_support: True            # False is used for local storage
    simultaneous_write_support: False   # Are simultaneous writes by multiple hosts supported in the submitted configuration
    simultaneous_read__support: True    # Are simultaneous reads by multiple hosts supported in the submitted configuration
  max_sequential_read: # Optional - GiB/s
  max_sequential_write: # Optional - GiB/s
  max_random_read: # Optional - GiB/s
  max_random_write: # Optional - GiB/s

PowerRequirements:
  dlio_client:
    quantity: # number of dlio_client nodes
    psu1_nameplate_power: # power in watts
    psu2_nameplate_power: # power in watts
    psu3_nameplate_power: # power in watts
    design_power: 2400
    num_active_psus: 2
    num_passive_psus: 1

  # All storage nodes need to be listed (data, metadata, etc) as well as any required backed switching
  storage_data_node:
    quantity: # number of storage data nodes
    psu1_nameplate_power: # power in watts
    psu2_nameplate_power: # power in watts
    psu3_nameplate_power: # power in watts
    design_power: 2400
    num_active_psus: 2
    num_passive_psus: 1
  backend_switch:
    quantity: 1
    psu1_nameplate_power: 700   # network PSU
    psu2_nameplate_power: 700   # network PSU
    design_power: 700
    num_active_psus: 1
    num_passive_psus: 1


# All nodes used need to be listed. Clients, Data storage, metadata, front-end, back-end, etc
Nodes:
  # Useful name for the client describing it's role in the system under test
  dlio_client:  # This can be DLIO Client, storage node, storage controller, AwesomeMarketingName_Type1, etc
    quantity: 8  # How many of this node
    hardware:
      model: SMC
      rack_units: 2
      power_supplies: 2
      psu_configuration: active/passive
      psu_rating: 1200
      memory_capacity: 256GB
      memory_configuration: 8x32GB
      cpu_qty: 2
      cpu_model: AMD 9555
      cpu_cores: 96
    networking:
      management:
        model: intel i210
        speed: 1Gbps
        qty: 1
    operating_system:
      name: Ubuntu
      version: 22.04 LTS
      release_date: 2022-04-12
      kernel_version: 5.15.0-56-generic
      cpu_architecture: x86_64
    tuning:
      # All non-default tunings for OS need to be listed
      mpi_configuration:
        environment_variables: <list>
        version: Open MPI 4.1.4
      sysctl_parameters:
        <list all non-default parameters>
  storage_data_node: # This can be DLIO Client, storage node, storage controller, AwesomeMarketingName_Type1, etc
    quantity: 8  # How many of this node
    hardware:
      model: SMC
      rack_units: 2
      power_supplies: 2
      psu_configuration: active/passive
      psu_rating: 1200
      memory_capacity: 256GB
      memory_configuration: 8x32GB
      cpu_qty: 2
      cpu_model: AMD 9555
      cpu_cores: 96
    networking:
      management:
        model: intel i210
        speed: 1Gbps
        qty: 1
    operating_system:
      name: Ubuntu
      version: 22.04 LTS
      release_date: 2022-04-12
      kernel_version: 5.15.0-56-generic
      cpu_architecture: x86_64
    tuning:
      mpi_configuration:
        environment_variables: <list>
        version: Open MPI 4.1.4
      sysctl_parameters:
        <list all non-default parameters>


